In [1]:
import pandas as pd

In [2]:
index_df = pd.read_csv('./machine_indices.csv', index_col=0)
index_df.head()

   train_start  train_end  test_start  test_end  length
0            0         79          80       113     113
1          114        318         319       455     341
2          456        486         487       695     239
3          696        666         667       952     256
4          953       2933        2934      4190    3237

In [7]:
index_df.iloc[:,[0, 1]]

      train_start  train_end
0               0         79
1             114        318
2             456        486
3             696        666
4             953       2933
...           ...        ...
1721      2007112    1405194
1722      2007421    1407280
1723      2010402    1409405
1724      2013437    1409564
1725      2013665    1409827

[1726 rows x 2 columns]

In [9]:
machine_df = pd.read_csv('./df_machine_sorted.csv', index_col=0)
machine_df.head()

,start_date,job_name,task_name,start_time,end_time,machine,runtime,plan_cpu,plan_mem,cap_cpu,cap_mem,cpu_usage,avg_mem,max_mem,avg_gpu_wrk_mem,max_gpu_wrk_mem,cap_cpu_100
104146,1970-01-28 15:32:43+08:00,9d28a91e7301a697bad12557,worker,2359963.0,2360077.0,0018d759f400ef5c0457ab9c,114.0,100.0,24.414062,96,384,35.636364,2.060832,32.796875,2.447969,4.208984,9600
139760,1970-01-29 16:01:19+08:00,74474bd870f2447ac939f9cd,worker,2448079.0,2448183.0,0018d759f400ef5c0457ab9c,104.0,600.0,29.296875,96,384,51.043478,0.780721,1.835938,0.441632,0.993164,9600
139884,1970-01-29 16:05:16+08:00,a75f2d5a26b8fff5724fdd6d,PyTorchWorker,2448316.0,2448477.0,0018d759f400ef5c0457ab9c,161.0,50.0,48.828125,96,384,59.483871,3.403646,37.934570,2.487621,6.723633,9600
169267,1970-01-30 11:54:59+08:00,0be403d9f0299123cb12c498,PyTorchWorker,2519699.0,2530096.0,0018d759f400ef5c0457ab9c,10397.0,300.0,292.968750,96,384,8021.102453,4.084847,37.093750,6.160750,6.541992,9600
174797,1970-01-30 14:50:21+08:00,a23b5d2cf2a5c94a8a798ac7,PyTorchWorker,2530221.0,2530335.0,0018d759f400ef5c0457ab9c,114.0,50.0,48.828125,96,384,81.285714,4.360521,37.631836,3.374715,6.723633,9600

In [20]:
machine_df.iloc[:, 0: 80]

,start_date,job_name,task_name,start_time,end_time,machine,runtime,plan_cpu,plan_mem,cap_cpu,cap_mem,cpu_usage,avg_mem,max_mem,avg_gpu_wrk_mem,max_gpu_wrk_mem,cap_cpu_100
104146,1970-01-28 15:32:43+08:00,9d28a91e7301a697bad12557,worker,2359963.0,2360077.0,0018d759f400ef5c0457ab9c,114.0,100.0,24.414062,96,384,35.636364,2.060832,32.796875,2.447969,4.208984,9600
139760,1970-01-29 16:01:19+08:00,74474bd870f2447ac939f9cd,worker,2448079.0,2448183.0,0018d759f400ef5c0457ab9c,104.0,600.0,29.296875,96,384,51.043478,0.780721,1.835938,0.441632,0.993164,9600
139884,1970-01-29 16:05:16+08:00,a75f2d5a26b8fff5724fdd6d,PyTorchWorker,2448316.0,2448477.0,0018d759f400ef5c0457ab9c,161.0,50.0,48.828125,96,384,59.483871,3.403646,37.934570,2.487621,6.723633,9600
169267,1970-01-30 11:54:59+08:00,0be403d9f0299123cb12c498,PyTorchWorker,2519699.0,2530096.0,0018d759f400ef5c0457ab9c,10397.0,300.0,292.968750,96,384,8021.102453,4.084847,37.093750,6.160750,6.541992,9600
174797,1970-01-30 14:50:21+08:00,a23b5d2cf2a5c94a8a798ac7,PyTorchWorker,2530221.0,2530335.0,0018d759f400ef5c0457ab9c,114.0,50.0,48.828125,96,384,81.285714,4.360521,37.631836,3.374715,6.723633,9600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1898518,1970-03-13 10:17:52+08:00,0a65401bad4458056daa19e1,worker,6142672.0,6144217.0,ffe93e263a503bff83bca28d,1545.0,400.0,11.718750,64,512,974.294872,9.049648,11.725586,2.930864,4.450195,6400
1899829,1970-03-13 10:54:21+08:00,68e69c824ef3739b2026fcda,PyTorchWorker,6144861.0,6159652.0,ffe93e263a503bff83bca28d,14791.0,1800.0,58.593750,64,512,2988.757432,3.445222,3.902344,2.675932,2.713867,6400
1899942,1970-03-13 10:56:37+08:00,5f3d159308880eb04fec33bb,PyTorchWorker,6144997.0,6159803.0,ffe93e263a503bff83bca28d,14806.0,1800.0,58.593750,64,512,2997.025641,3.423235,3.907227,2.664026,2.713867,6400
1936024,1970-03-14 12:38:08+08:00,686fbdbc88f3769f073eb527,worker,6237488.0,6238995.0,ffe93e263a503bff83bca28d,1507.0,600.0,29.296875,64,512,61.105263,1.408332,8.894531,1.136205,4.207031,6400
1952195,1970-03-15 01:09:06+08:00,f8ce59e595168642575b09a3,worker,6282546.0,6282582.0,ffe93e263a503bff83bca28d,36.0,50.0,0.781250,64,512,40.600000,0.238281,0.464844,0.000000,0.000000,6400

In [24]:
test = machine_df.iloc[:, ]

In [35]:
train_start_index = index_df['train_start'].values
train_end_index = index_df['train_end'].values

for idx in range(len(index_df)):
    machine_df.iloc[:, train_start_index[idx]:train_end_index[idx]]